
COMPONENTS:
  - CLASS: AddPDFInfoComponent
    KWARGS: {}
  - CLASS: ImageDetectorComponent
    KWARGS: {}
  - CLASS: LayoutDetectorComponent
    KWARGS: 
      cover_prev_anns: True
      cfg_path: 'config/layout_detector_config.yaml'
      method: 'd2layout'
      config_overwrite: ['PT.LAYOUT.FILTER=["table", "figure"]']
  - CLASS: LayoutDetectorComponent
    KWARGS:
      cover_prev_anns: True
      cfg_path: 'config/table_detector_config.yaml'
      method: 'detr'
  - CLASS: LayoutDetectorComponent
    KWARGS:
      cover_prev_anns: True
      cfg_path: 'config/layout_detector_config.yaml'
      method: 'd2layout'
      config_overwrite: ['PT.LAYOUT.FILTER=["text", "title", "list", "table"]']
  - CLASS: NMSComponent
    KWARGS:
      cfg_path: 'config/nms.yaml'
  - CLASS: OCRComponent
    KWARGS:
      cfg_path: 'config/tesseract_config.yaml'
      method: 'tesseract'
  - CLASS: WordUnionComponent
    KWARGS: 
      unite: [table]