

COMPONENTS:
  - CLASS: AddPDFInfoComponent
    KWARGS: {}
  - CLASS: LayoutDetectorComponent 
    # find bboxes for everything exept for figure and table. These are most difficult, so we do them later
    # and first get rid of things we can detect reliable
    KWARGS:
      cover_prev_anns: False
      cfg_path: 'layout_detector_config.yaml'
      method: 'd2layout'
      config_overwrite: ['PT.LAYOUT.FILTER=["table", "figure"]']
  - CLASS: LayoutDetectorComponent
    # cover previous annotations with white space and then detect tables!
    KWARGS:
      cover_prev_anns: True
      cfg_path: 'table_detector_config.yaml'
      method: 'detr'
  - CLASS: LayoutDetectorComponent
  # cover previous annotations with white space and then detect figures!
    KWARGS:
      cover_prev_anns: True
      cfg_path: 'layout_detector_config.yaml'
      method: 'd2layout'
      config_overwrite: ['PT.LAYOUT.FILTER=["table", "title", "list", "text"]']
  - CLASS: NMSComponent
    KWARGS:
      cfg_path: 'nms.yaml'
  - CLASS: OCRComponent
    KWARGS:
      cfg_path: 'tesseract_config.yaml'
      method: 'tesseract'
  - CLASS: WordUnionComponent
    KWARGS: 
      unite: [table]