layout_analysis:
  CONFIG_PATH: 'meri/layout/config/good_pipeline.yaml'
transformer:
  FORMAT: 'markdown'
  KWARGS: 
    table_extraction_method: 'toimage'
extractor:
  METHOD: 'populate_schema'
  KWARGS:
    chunks_max_characters: 1000
    chunk_overlap: 2
    model: 'gpt-4o'